import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "../store/StoreProvider";
import LenisProvider from "../components/LenisProvider";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      {/* Blocking script: apply saved theme before first paint to avoid FOUC */}
      <script dangerouslySetInnerHTML={{ __html: `
        (function() {
          try {
            var t = localStorage.getItem('hc-theme') || 'light';
            var isDark = t === 'dark' || (t === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
            if (isDark) document.documentElement.classList.add('dark');
          } catch(e) {}
        })();
      ` }} />
      
      <body>
       <StoreProvider>
         <LenisProvider>
           {children}
         </LenisProvider>
        </StoreProvider>
        <Toaster position="bottom-right" />
      </body>

    </html>
  );
}
